---
- hosts: all
  become: true
  tasks:
    
    - name: update repository index
      ansible.builtin.apt:
        update_cache: yes

    - name: install openSSL package
      ansible.builtin.apt:
        name: openssl
        state: present
    
    - name: install support for php
      ansible.builtin.apt:
        name: libapache2-mod-php