---
- name: Install and start Apache web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    
    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true